### ISSUE TITLE
Add leading underscores to all private modules

### ISSUE THREAD

**Issue by paulmelnikow** [lace/polliwog#149]
This makes code break now if it's not using the canonical imports, rather than breaking when they're moved down the line.

**Comment by MCilento93** [comment]
How import CompositeTransform() class?

Assume I have a cloud of points and want to apply at low level a CompositeTransform() class, I don't realize how to import this class.

**Comment by paulmelnikow** [comment]
```py
from polliwog import CompositeTransform
```

**Comment by MCilento93** [comment]
> ```python
> from polliwog import CompositeTransform
> ```

![image](https://user-images.githubusercontent.com/66259011/112717961-293b9d00-8ef0-11eb-8635-984328e49b88.png)

I am sorry for the trivial questions but the documentation for increase the userability of the package would boost the trial and error curve :/

**Comment by MCilento93** [comment]
> > ```python
> > from polliwog import CompositeTransform
> > ```
> 
> ![image](https://user-images.githubusercontent.com/66259011/112717961-293b9d00-8ef0-11eb-8635-984328e49b88.png)
> 
> I am sorry for the trivial questions but the documentation for increase the userability of the package would boost the trial and error curve :/

Am I wrong in something?

**Comment by MCilento93** [comment]
> > > ```python
> > > from polliwog import CompositeTransform
> > > ```
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/66259011/112717961-293b9d00-8ef0-11eb-8635-984328e49b88.png)
> > I am sorry for the trivial questions but the documentation for increase the userability of the package would boost the trial and error curve :/
> 
> Am I wrong in something?

Solved. 

``` python

x0y0=np.array([0.0, 0.0, 0.0])

from polliwog.transform import CompositeTransform

transform = CompositeTransform()
transform.translate(np.array([0.0, 0.0, 1.0]))
x0y0z0=transform(x0y0)
```

**Comment by paulmelnikow** [comment]
What version of polliwog are you running? Be sure you are on **1.0.0b11**.

```
> python3
Python 3.8.6 (default, Oct 27 2020, 08:57:44)
[Clang 12.0.0 (clang-1200.0.32.21)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from polliwog.transform import CompositeTransform
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'CompositeTransform' from 'polliwog.transform' (/Users/pnm/code/polliwog/polliwog/transform/__init__.py)
>>> from polliwog import CompositeTransform
>>> import polliwog
>>> polliwog.__version__
'1.0.0b11'
```

**Comment by paulmelnikow** [comment]
Have you seen the documentation, by the way? https://polliwog.readthedocs.io/en/latest/

**Comment by MCilento93** [comment]
> What version of polliwog are you running? Be sure you are on **1.0.0b11**.
> 
> ```
> > python3
> Python 3.8.6 (default, Oct 27 2020, 08:57:44)
> [Clang 12.0.0 (clang-1200.0.32.21)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from polliwog.transform import CompositeTransform
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: cannot import name 'CompositeTransform' from 'polliwog.transform' (/Users/pnm/code/polliwog/polliwog/transform/__init__.py)
> >>> from polliwog import CompositeTransform
> >>> import polliwog
> >>> polliwog.__version__
> '1.0.0b11'
> ```

Correct,
I uploaded to newer version and the importing is like you wrote.


> Have you seen the documentation, by the way? https://polliwog.readthedocs.io/en/latest/

I was on /stable and looks slightly different from the one I am reading now.
Thank you,
I will let you know :)
