### ISSUE TITLE
Line intersect ... clarification

### ISSUE THREAD

**Issue by MCilento93** [lace/polliwog#216]
Hello everybody and thank @paulmelnikow and the rest of your staff for this lovely geometry package.

I am doing some tests to undestand well the basis and performances.
Though, I the method line.intersect gives always results even when the two line have not a intersection point. What's the meaning? 
In the example below the lines below to two parallel planes.

``` python
# 4 Points of a box on xy plane
x0y0=np.array([0.0, 0.0, 0.0])
x1y1=np.array([1.0, 1.0, 0.0])
x1y0=np.array([1.0, 0.0, 0.0])
x0y1=np.array([0.0, 1.0, 0.0])

line1 = Line.from_points(x0y0,x1y1) # line on xy plane
line2 = Line.from_points(x1y0,x0y1) # line on xy plane

line1.intersect_line(line2) # right intersection point on the xy plane as expected

# now let's shift the plane of 1 along z
from polliwog.transform import CompositeTransform
transform = CompositeTransform()
transform.translate(array(0, 0, 1))
x0y0z1=transform(x0y0)
x1y1z1=transform(x1y1)

line3 = Line.from_points(x0y0z1,x1y1z1) # on xy plane but z++, no expected intersection
line3.intersect_line(line2) # !! got array([-0.8660254, -0.8660254,  1.       ])
```

**Comment by paulmelnikow** [comment]
Hi! Thanks for the report. This is an unhandled edge case. It should be fixed with #217.

**Comment by MCilento93** [comment]
Good to hear you were already on this fix!
I will eventually open new issue requests referencing the code I find something to work on.
Cheers, and you can even close this thread since the #217 is open.

**Comment by paulmelnikow** [comment]
@MCilento93 Could you confirm that #217 fixes the issue you reported?

**Comment by MCilento93** [comment]
> @MCilento93 Could you confirm that #217 fixes the issue you reported?

Hello,
I tested with the same test above reported leading the same error in interception point.

Tested on release 1.0.0b12 and 0.12.0 :(

**Comment by paulmelnikow** [comment]
#217 has not been merged, so it is not in the release, because I want to test it first :)

`pip3 install 'polliwog @ git+https://github.com/lace/polliwog.git@fix-intersect-line-edge-case'`

**Comment by MCilento93** [comment]
I installed by mean of `pip install git+https://github.com/lace/polliwog.git@fix-intersect-line-edge-case` though.

The test reported above worked fine :) It leads to None intersection. The same occurs if the lines are aligned but not intersecting.
If the lines aligned intersect each other instead, I do not get always positive results. Check this sample ... from a formal point of view I expect a line from the intersection (in other case if lines are contiguous the intersection is a point, but not 100% cases it works).

```python
line4=Line.from_points(x0y0,x0y1)
line5=Line.from_points(np.array([0,.5,0]),np.array([0,3,0]))
print(f"Intersection {line5.intersect_line(line4)}") # !! collinear case, expected multiple intersections?
```

**Comment by paulmelnikow** [comment]
https://github.com/lace/polliwog/blob/261ccd6c6db22cae5d4af6d3498e09202b544265/polliwog/line/test_line_intersect.py#L29-L32

The collinear case should return `None`. Is that what's happening?

**Comment by MCilento93** [comment]
> https://github.com/lace/polliwog/blob/261ccd6c6db22cae5d4af6d3498e09202b544265/polliwog/line/test_line_intersect.py#L29-L32
> 
> The collinear case should return `None`. Is that what's happening?

Yes. 
But if are collinear in just a point of intersection the method returns the intersection point

**Comment by paulmelnikow** [comment]
Cool. If you need to detect collinearity, we could maybe add an option to throw an exception. Let me know if that’s something you need.

What do you mean, collinear in just a point of intersection? Can you give a (self-contained) example?

**Comment by MCilento93** [comment]
> Cool. If you need to detect collinearity, we could maybe add an option to throw an exception. Let me know if that’s something you need.
> 
> What do you mean, collinear in just a point of intersection? Can you give a (self-contained) example?

You so kind. Actually I don't need this feature.

With collinear in a point I mean, for the sake of example, first line going from (0,0) to (1,0) and second line passing through (1,0) to (2,0).

**Comment by paulmelnikow** [comment]
> With collinear in a point I mean, for the sake of example, first line going from (0,0) to (1,0) and second line passing through (1,0) to (2,0).

Ah, well, a line extends infinitely, so they are collinear everywhere, not just at that point.

We could add another function to handle _line segment_ intersection if that’s something you need.
